env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:react/jsx-runtime
  - plugin:jsx-a11y/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
settings:
  react:
    version: detect
plugins:
  - react
  - "@typescript-eslint"
rules:
  '@typescript-eslint/no-non-null-assertion': 0 # 允许!断言
  react/prop-types: 0 # TypeScript 无视此规则
