printWidth: 120 # 每行长度
tabWidth: 2 # tab长度
useTabs: false # 是否使用tab
semi: false  # 是否使用分号
singleQuote: true # 是否使用单引号
quoteProps: "as-needed" # 对象属性何时需要引号
jsxSingleQuote: false # jsx是否使用单引号
# trailingComma: "es5"
bracketSpacing: true  # 对象两端是否需要空格
bracketSameLine: true # jsx起始标签结束括号是否不换行
arrowParens: "always" # 箭头函数参数何时需要括号
